### PR TITLE
Display expired/missed tickets in /vsp table.

### PR DESCRIPTION
**Pull request by jholdstock**
## :warning: This should not be deployed before decred/dcrwebapi#180 and all VSPs are running vspd >=1.3.0

Screenshot from 2023-10-26 09-49-14

### CODE REVIEW

**Comment by xaur** [comment]
Nice! I have some ideas:

1\. `Missed %` column is much more interesting than `Expired %` (which should converge to 0.5% iirc), is `Expired % ` useful on this page?

2\. How about renaming `Voting` to `Live` for consistency with e.g. dcrwallet outputs? (unless "Voting" is commonly used now in UIs, not sure)

3\. How about also exposing block height? `Last Updated` is "when we got last response from the VSP" regardless of its status, while block height clearly shows if it's stalled or on current chain tip. Personally I find block height more useful for choosing a VSP, if it has stalled it may not vote my tickets. Perhaps height could replace `Last Updated` alltogether.

**Comment by jholdstock** [comment]
1. Good point. For the same reason, the absolute number of expired tickets is probably not a useful metric either. I'm tempted to remove that too, what do you think? It'd probably make the table easier to parse.
1. vspd uses "Voting" as a distinct term because it includes both immature and live tickets. I'm fine with using "Live" here though for consistency/simplicity - will update.
1. I don't think just displaying the block height is useful unless it has some extra context - eg. what is the correct block height meant to be? It isn't easy to parse a column of very similar 6-7 digit numbers and know which ones are correct/incorrect. I think it would need some extra design elements. We can do that as a separate change if it is deemed worthwhile.

**Comment by xaur** [comment]
1\. Yes I'd remove it. `Missed` and `Missed %` will essentially replace `Revoked` and `Revoked %`. Not having too many columns is good too. If the need fir `Expired` arises it can be added back.

2\. Ah I didn't know tha "Voting" includes immature. I suggested "Live" because it sounds easier to understand (like they are "up" or "online", and also not "voting" *right now* but rather *waiting* when they can vote). I don't mind either now.

3\. "what is the correct block height meant to be?" - I think 1-2 numbers not matching the other 13 would be enough to alert the user to check something else without even knowing what "block height" is. Maybe a "Check the latest block at the block explorer" link would be enough. But yeah this can be done in another PR.

**Comment by jholdstock** [comment]
Updated with suggestions

Screenshot from 2023-10-28 09-26-28

**Comment by xaur** [comment]
Nice! Another small thing is `Age` -> `Launched` may read a bit better. Not blocking this PR ofc.

**Review by dajohi — APPROVED** [review]

**Pull request merged**
