### PR TITLE
Added Latest News Articles

### PR DESCRIPTION
**Pull request by nickboariu**

### CODE REVIEW

**Comment by nickboariu** [comment]
I just read the comments from the previous updates to coverage.yaml, hopefully this commit is in-line with the aesthetics. I took the liberty of fixing up some inconsistencies in previous commits.

**Comment by dajohi** [comment]
please rebase this.

**Comment by xaur** [comment]
Hey @nickboariu thanks for the contribution!

Our process of updating the News page is still being hashed out and it's not well documented. Based on what we have figured out so far I can comment on this PR:

- Stylistic tweaks to earlier titles may be a good idea but it's better done separately from adding new stuff.
- Other than fixing capitalization style, so far we have preserved the original title and did not try to replace it with a more meaningful summary. I suggest to keep `Title` for the original title. Adding additional interpretation of the story may be useful though, e.g. in its own `Params.summary` field.
- We are trying to find a balance between News/Coverage being too silent and too spammy. For the BR elections story, we already have two items for [thefintechtimes.com](https://thefintechtimes.com/new-use-for-blockchain-setting-the-record-straight-in-political-battles/) and [invezz.com](https://invezz.com/news/2022/11/11/video-blockchain-and-elections-jake-yocom-piatt/). We have evaluated the two more stories this PR is adding (br.beincrypto.com and cointelegraph.com.br) and decided that the two selected ones should be enough for that time frame.
- [Sustainable crypto alternatives](https://thefintechtimes.com/sustainable-crypto-alternatives-to-mining-with-decred-sellix-and-omnia-markets/) story looks like smaller mention/commentary - I think these are not "Decred enough" to go in News.
- The latest [Cryptonews](https://cryptonews.com/exclusives/jake-yocom-piatt-co-founder-of-decred-on-blockchain-fixing-political-voting-campaign-spending-and-privacy.htm) piece looks like a full interview with a project representative so it's a good candidate.

Sorry for the wasted work with the closed PR but contributions to improve News are still welcome. Our current workflow only does monthly updates and more frequent updates might not hurt. I'll do another PR soon that will show where we're heading.

**Comment by xaur** [comment]
I included some of these fixes for `externalSource` field in #1102

**Pull request closed without merging**
