### PR TITLE
Create a landing page for new Matrix users #452

### PR DESCRIPTION
**Pull request by ZeroASIC**
This is the update for Issue #452.  It creates a new landing page for Matrix, an accompanying page for Slack, and a few fixes to go along with them.

It would be really useful if we could get slack.decred.org pointed at the newly created /slack/ directory so we can make updates to it.  The existing page is pretty far out of date and we don't have to a way to fix it at the moment.  If this gets merged in as is then I can create a new issue to handle that transition, but it would take an admin to make it happen.  Alternatively the updated index.html in /slack/ could be moved to slack.decred.org, but it has paths pointing to /content/ instead of /assets/.

### CODE REVIEW

**Comment by dajohi** [comment]
rebase

**Comment by ZeroASIC** [comment]
It didn't merge completely so I had to add a commit to clean it up.  It looks good now.

**Comment by ZeroASIC** [comment]
@s-ben Can you take a look at the feedback from @RichardRed0x?

**Comment by s-ben** [comment]
@ZeroASIC , sorry for the delay. Was traveling over the holidays and just getting back. 

Finding the rooms was very confusing for me as well. I suggest adding the following text below  'Login to Decred homeserver':

> To browse Decred rooms, click the directory button in the ’Rooms’ panel (left-hand side).    

If we want an image, I've created a screenshot with more concise text:

> To browse Decred rooms, click the directory button in the ’Rooms’ panel.

matrix_rooms

**Comment by ZeroASIC** [comment]
I combined the two ideas.  I posted a new screenshot in the original issue.

**Comment by s-ben** [comment]
Posted feedback on original issue. tldr; I vote for going with just text.

**Comment by ZeroASIC** [comment]
Updated the link to the correct link and correct text.  Please review and/or merge.

**Pull request merged**
