### PR TITLE
Update exchanges.yml

### LINKED ISSUE #1087: Kucoin now accepting DCR deposits again. Should be added to Exchanges
See their announcement: https://www.kucoin.com/pl/news/pl-pl-en-kucoin-opens-mainnet-dcr-tokens-deposit-and-withdrawal-services-20220924

### LINKED ISSUE #1133: Remove Hotbit
Hotbit is closing:

- https://twitter.com/Hotbit_news/status/1660496999458963458
- https://help.hotbit.io/hc/en-us/articles/14750194236823-It-s-time-to-take-a-bow

### LINKED ISSUE #1134: Add Huobi back
We removed Huobi in #1081 after they [announced](https://web.archive.org/web/20221002130913/https://www.huobi.com/support/en-us/detail/104917015223952) they will delist DCR and other privacy coins. Looks like that never happened and they removed the announcement page. [DCR/USDT](https://www.huobi.com/en-us/exchange/dcr_usdt) seems live and CoinMarketCap/CoinGecko report non-zero volumes for DCR and all other coins from that announcement.

There may be other reasons to not re-list Huobi, I'm not sure. Thoughts?

### PR DESCRIPTION
**Pull request by Clopas**
closes #1134
closes #1133
closes #1087

### CODE REVIEW

**Comment by Clopas** [comment]
I also added 4 new exchanges: Bitbns, Bingx, Coinex, Mexc
 The criteria to add are as below.
They should comply with all three of the following:
1. In the top 20 in terms of the reported DCR 24-hour trading volume. (source: coinmarketcap)
2. In the top 20 in terms of the liquidity score. (source: coinmarketcap)
3. Has a chart in Tradingview

**Review by jholdstock — CHANGES_REQUESTED** [review]
One of the important criteria is that a DCR community member must have used the exchange to validate that withdrawals and deposits are actually possible.

I suggest removing the 4 new exchanges from this PR and adding them in a new one, that way the additions can be discussed/reviewed/merged separately.

**Comment by Clopas** [comment]
Thank you for the review. I didn't realise that before. I will open a separate PR for the new exchanges to discuss, etc.

**Comment by xaur** [comment]
Yeah we don't want to send people to exchanges with deposit or withdrawal issues from https://decred.org/exchanges/ . Unfortunately they happen. I believe in this case the friction to add new items is justified.

**Review by jholdstock — APPROVED** [review]

**Comment by jholdstock** [comment]
Thanks @Clopas!

**Pull request merged**
