### PR TITLE
add cryptopower to /wallets

### LINKED ISSUE #1143: Add Cryptopower to /wallets
https://github.com/crypto-power/cryptopower

### PR DESCRIPTION
**Pull request by dreacot**
closes #1143 https://github.com/crypto-power/cryptopower/issues/127

Screenshot 2023-10-05 at 10 25 05 AM

### CODE REVIEW

**Comment by xaur** [comment]
Missing `.` at the end of the text label.

Similar to #1141 I suggest to change the first link like: [Download and release notes](https://github.com/crypto-power/cryptopower/releases/tag/release-v1.0.0) to better communicate what is behind the link. "GitHub" is alien and confusing for end users looking to *download* the app.

Some ideas for the second link:

- "Source code" -> https://github.com/crypto-power/cryptopower
- App's website
- Twitter account where to follow for updates

**Comment by dajohi** [comment]
needs rebase

**Comment by dreacot** [comment]
@dajohi rebased✅

@xaur changes effected

**Review by jholdstock — APPROVED** [review]
Looks fine to me but needs another rebase.

**Comment by dreacot** [comment]
@jholdstock rebased

**Pull request merged**
