### PR TITLE
Add icons to Downloads page

### LINKED ISSUE #328: Mobile/desktop icons for downloads
Adding small icons to distinguish between software meant for mobile devices would be useful on https://decred.org/downloads/ we have a number of integrations that are being finished up so making it clear what software runs where would be nice.

### PR DESCRIPTION
**Pull request by Jujhar**
Fixes #328 

Windows, Mac, Linux, phone, and desktop icons have been added, I left out the mining and command-line tools to keep things neat.

Screen Shot 2019-06-03 at 10 47 54 PM

----
Screen Shot 2019-06-03 at 10 48 03 PM

### CODE REVIEW

**Comment by linnutee** [comment]
This isn't consistent with the rest of the site design. 
Proposed icons are conflicting due to showing both os's logos and device types as well are of several different visual styles.

The approach I had in mind was to use the same filtering pattern as on https://decred.org/exchanges/ with two groupings – mobile os's and desktop os's. 

The item cards would likely stay the same or may consider adding small legends on top right corner besides the 3rd party or dcr developed legends. This needs some trying out to make sure it won't look overly busy.

Screenshot 2019-06-04 at 19 23 16

**Comment by Jujhar** [comment]
There are three groups, phone, desktop, and both. 
You sure sorting is needed there are only about 6 elements?

Maybe we can change all the icons to the grey colour of the apple logo with slight dabs of blue, that might work making them all consistent?

There is already the small legends on the top right, with the dcr or 3rd label on them.

**Comment by linnutee** [comment]
The sorting happens between both mobile and desktop os's: macos, linux, windows; ios and android. Only real issue here is a clear distinction between macos and ios, but this can be solved by proper grouping and potentially having a minor differentiation between ios and android vs desktop os's. 

3rd party and DCR developments don't need to be sorted as that can be always seen on the cards.

Regarding design – first reference should always go to the DCR iconset (found in dcrdesign repo) and the accompaning identity guidelines. If dealing with logos as icons (ie. apple) any monotone version needs to use the existing DCR color swatches not a random color pick.

**Comment by Jujhar** [comment]
I am developing a new set like a grey version attached if you know a better monotone match please suggest. 

Screen Shot 2019-06-14 at 6 23 33 AM


Or a darker variant eg:
Screen Shot 2019-06-14 at 6 26 57 AM


If you have a quick mockup of the sorting implementation, if you want to proceed with that, please provide. I think a better approach might be to have a image backdrop not necessary near the 3rd party icons but bigger in the center. Or maybe keep it where it is in the bottom and separate the section by changing the background of that small bottom section of the card to a light blue and make the icons grey/black?

**Comment by Jujhar** [comment]
Looks better @linnutee 

downloads

**Comment by linnutee** [comment]
Ok this isn't getting anywhere, best to halt as the feedback is missed + there's going to be some content changes affecting the Downloads page. 

Having all those icons on a single card is way overloading, as well the proposed icons don't fit the common icon set at all.

**Pull request closed without merging**
