### PR TITLE
Fix typo on start page. From 'Misson' to 'Mission'

### PR DESCRIPTION
**Pull request by magnus-staberg**
I don't know how the translation works and I haven't tested it. Someone with appropiate knowledge please make sure this PR doesn't break anything.

### CODE REVIEW

**Comment by peterzen** [comment]
It's OK to merge/roll out as long as the translation files are not updated.

**Comment by magnus-staberg** [comment]
@peterzen Changes on *.po files have been reverted.

**Comment by peterzen** [comment]
Cool, thanks!

**Comment by dajohi** [comment]
@magnus-staberg Can you squash down to 1 commit please?

**Comment by magnus-staberg** [comment]
@dajohi No problem, it's squashed.

**Pull request merged**
