### PR TITLE
Improve stakepool list

### LINKED ISSUE #156: Stakepool user count
2017-10-25-060421_310x223_scrot

The list of stake pools on decred.org currently shows the total user count for each pool. This figure is misleading IMO since typically half of these "users" don't actually stake. I think it'd make more sense to show the *active* user count as a metric.

The active user count is computed as [any user who has submitted an address](https://github.com/decred/dcrstakepool/blob/master/models/user.go#L98-L100). Ideally, I think it should be any user who has bought at least 1 ticket on the pool because one can submit an address then never actually stake.

Thoughts?

### PR DESCRIPTION
**Pull request by infertux**
- add proportion missed
- sort by proportion live
- compact rows
- show active user count instead of total user count

---

Before:

2018-01-13-191618_1023x748_scrot

After:

2018-01-13-185842_1150x637_scrot

[Closes #156]

### CODE REVIEW

**Comment by xaur** [comment]
Great! Is it possible to also add "pool age" that shows how long the pool operates? Together with Missed % it would give a good idea bout pool reliability. (previously requested in #55).

**Comment by infertux** [comment]
@xaur Good idea. I see we can find the launch dates [here](https://github.com/decred/dcrwebapi/commit/09113670a5b411c9c0c988e5a8ea627ee00ac007). I'll add it tomorrow.

**Comment by infertux** [comment]
Done: 
2018-01-15-105804_96x515_scrot

**Comment by peterzen** [comment]
Looks good - though please squash the commits together when you get a chance.

**Comment by infertux** [comment]
> We intentionally make the sorting random so it doesn't look a certain pool is being advocated/pushed for (although we do of course want people to spread tickets out which is why the warning is there about pools above 5%)

Fair enough, I removed it. However I kept the sort by network so that testnet pools are pinned to the bottom of the table.

Also rebased and squashed.

2018-01-16-041804_1131x527_scrot

**Comment by xaur** [comment]
Thanks was missing this! Also for cutting 42 lines in the process ;)

**Comment by infertux** [comment]
@jolan Cool, I just sent a PR for dcrwebapi. I'll update this one once it's merged.

**Comment by linnutee** [comment]
Some design feedback before this can be merged. Based on the previous screenshot.

34971749-8cf98668-fa74-11e7-8cec-943090fdf648 copy

1. `ID`needs to be left aligned with the rest of the first column. 
2. All of the columns that use `right aligned text` text, need to be horizontally aligned to the right with the title. (Proportion, Live, Immature, Voted, Missed, Proportion Missed, Pool Fees, Active Users, Launched)
Preview:
screen shot 2018-01-30 at 21 30 06
3. Remove `network` column. Best to things clear and simple. I don't see a need for this one as there's only one testnet stakepool, very unlikely to cause confusion. Or would even consider removing the testnet stakepool from this list altogether. 
4. `Proportion missed` rename to `Missed %`, this way it can be on a single line. All of the titles should be fitted to on a single line. 
5. `Pool Fees`rename to `Fees`, same reason.
6. `Active Users `rename to `Users`, same reason.

**Comment by dajohi** [comment]
@infertux Can you address @linnutee's concerns?

**Comment by infertux** [comment]
@dajohi Sure, just waiting on https://github.com/decred/dcrwebapi/pull/16 in case it needs changes. Could you review it please?

**Comment by dajohi** [comment]
@infertux merged and running

**Comment by infertux** [comment]
@dajohi @linnutee Ready to review/merge. New screenshot:

2018-03-27-123514_980x466_scrot

**Pull request merged**
