### PR TITLE
Feature/add eslint

### PR DESCRIPTION
**Pull request by oktapodia**
Eslint configuration added #132 

Sorry about the number of modification, it will be a nightmare to review...

I decided to exclude some files like `decred.js` because it looks like a vendor compiled file

The eslint configuration is also permissive at this point to reduce the number of lines to review...

### CODE REVIEW

**Comment by dajohi** [comment]
Should this be closed or at least rebased?

**Comment by oktapodia** [comment]
I think we should close it

**Comment by peterzen** [comment]
Yes close please

**Comment by jolan** [comment]
Closing per request.

**Pull request closed without merging**
