### PR TITLE
update exchanges list

### PR DESCRIPTION
**Pull request by degeri**
instaex.io down
fexpro.net ssl error
changenow.io dcr listed but not supported.

### CODE REVIEW

**Review by jholdstock — CHANGES_REQUESTED** [review]
Checking now - I see Decred on changenow.io. [Related discussion](https://github.com/decred/dcrweb/issues/458#issuecomment-581440543)

I support removing the other two.

**Comment by degeri** [comment]
actually no 

image

**Comment by jholdstock** [comment]
@NowPaymentsIO are you able to comment on this?

**Comment by NowPaymentsIO** [comment]
Hello! Thank you for your comments! 

NOWPayments does support DCR, but only for the pay-out at the moment. Basically, it means that if you are a Merchant using NOWPayments for your store, you can indicate DCR as the outcome currency and have all your payments converted into DCR, but your customers cannot make payments/deposits in DCR. 

It is a temporal situation though, the team is already working on solving it.

**Review by jholdstock — APPROVED** [review]

**Pull request merged**
