### PR TITLE
Added SwapSwop to the list of Exchanges

### PR DESCRIPTION
**Pull request by antonegorov**
Added SwapSwop to the list of Exchanges

### CODE REVIEW

**Review by jholdstock — APPROVED** [review]
Approving changes in the PR, however I have never heard of swapswop.io and don't know of any Decred community member who has validated it.

**Comment by antonegorov** [comment]
> Approving changes in the PR, however I have never heard of swapswop.io and don't know of any Decred community member who has validated it.

Our team has been working since March 2020 and we are a relatively young project. Before, we don't have marketing at all, and now we are fixing this situation.
P.S.: I will ask the CMO to contact you and make a video call to get acquainted.

**Comment by antonegorov** [comment]
These are trust guys. They were recently added to their pages at https://blockchair.com/ @jholdstock

**Comment by dajohi** [comment]
Looks like SwapSwop only supports receiving DCR and only with "floating" and not "frozen".  Closing.

**Comment by antonegorov** [comment]
Hello.

I'm afraid the configuration varies depending on many factors. Right now, within risk management and asset management, this condition of providing exchanges is optimal.

**Pull request closed without merging**
