### PR TITLE
Remove contributors page.

### PR DESCRIPTION
**Pull request by jholdstock**
As this topic has been discussed for quite some time, and there seems to be good consensus, I've just opened a PR to do it.

Some justification:

- Who qualifies as a "contributor" is subjective, and necessarily a centralized decision made by gatekeepers.
- List of contributors is really out of date. Active contributors are missing, and many inactive ones are still listed.
- Contact information easily falls out of date. Not only is this unhelpful, but it can lead to security issues like account hijacking. Almost everybody is available on Matrix anyway.
- The process of getting contractor portraits created is cumbersome.
- Having a contributor page is passé

PR is currently broken into separate commits because that is how I worked on the changes. They can be reviewed independently, but I suggest they are squashed before merging.

### CODE REVIEW

**Comment by xaur** [comment]
Linking some discussion on this topic:

- Idea to add a [Past Contributors page](https://github.com/decred/dcrweb/issues/744) as a kind of [Hall of Fame](https://github.com/decredcommunity/issues/issues/52), to keep good memory of people who helped build Decred even if they left. This would differ from the Contributors page by not attempting to capture the ever-changing "active" set and be almost "append-only". I still think it's a good idea, but if dcrweb doesn't want it we could build it in some other place.
- [Clarify that only active contributors are listed](https://github.com/decred/dcrweb/issues/781)
- [DJ Production Guidelines](https://github.com/xaur/decred-news/blob/docs/guidelines.md#why-new-contributors-at-decredorg-are-not-reported) sections that were influenced by how the Contributors works. Specifically, we decided to stop reporting additions and removals to/from the page in DJ because it did not reflect the "active list" of contractors (reasonable expectation IMO) and the rules to get listed/delisted were unclear.

**Comment by xaur** [comment]
I think the reasons to remove the Contributors page are solid.

> The process of getting contractor portraits created is cumbersome.

I guess the portraits were the best part of it. I heard some excitement from people getting those, and I still see them used as avatars on social media. It means these portraits are great for community building. We can continue making them regardless of the page though.

Just look how awesome it is :)



Source: https://github.com/decred/dcrdesign/issues/189#issuecomment-580495280

**Comment by jzbz** [comment]
Long overdue.

**Comment by jholdstock** [comment]
I do love the portraits and I'm glad to have received one. I'm saving the entire folder of them in case they are ever useful for a future project.

As for hall of fame/legacy, its a nice idea. A lot of that info is captured in Git history, and release notes for most Decred software contains list of contributors. It isn't as easy to digest as a single web page, but at least the info is not being lost forever.

**Review by dajohi — APPROVED** [review]

**Pull request merged**
