### PR TITLE
Localization implementation

### PR DESCRIPTION
**Pull request by peterzen**
- Added gettext tags
- Added `grunt` tasks for extracting/compiling `gettext` catalogs
- Added localized catalogs
- Added basic README describing translation workflow 
- Added Transifex workflow scripts
- Dockerized deployment setup

### CODE REVIEW

**Comment by jcvernaleo** [comment]
A more general comment on this, is there a reason to keep the dockerfiles here and not in decred/dcrdocker?  I'd prefer if we keep our dockerfiles somewhat centralized (and ultimately published in the decred org on docker hub).

**Comment by peterzen** [comment]
From a deployment perspective it seems more intuitive to keep all the files (code+configuration) required for deploying/running a particular service in a self-contained repository, so that the deploy workflow doesn't involve multiple repositories.  Most services require configuration files in addition to the `Dockerfile`, the docker setup is the simplest if these are in same directory and you don't have to reference to a separate build context.

It's also more intuitive from a maintenance PoV – if a change is needed that involves a change in both the code and the server config (for instance, we need to tweak the i18n setup in `dcrweb`) then it can be made in a single atomic commit (as opposed to 2 in separate repositories).  Same issue if, for example, the application's build process changes slightly and needs a change in the Dockerfile then if they're both in the same repository the consistency of the build is guarranteed and you can easily revert to an earlier state (if the docker config is in another repo then this can get tricky.) 

You can still push the images to docker hub this way – actually most images on there link to the source repo they were built from.

**Comment by peterzen** [comment]
Maybe we can ask @dajohi what his preference is – in this case he's the customer :)

**Comment by jcvernaleo** [comment]
Somewhat depends on what is in the images and how you plan on creating them.

Personally I like when the Dockerfile has the commit has in it of the code it is going to use (like the insight one) so that does not work with this model.

I agree that having the dockerfile in the repo can be easier for dev (again, depending on what is in the dockerfile and how it gets used) but from a production standpoint I'm not so sure.  Building a new production image is (and should be) a different thing than accepting a PR on a code repo (which is part of why I liked keeping the docker stuff together).

A single docker repo also encourages us to keep the dockerfiles as similar as possible which I think should be a goal.

**Comment by peterzen** [comment]
I agree that keeping all dockerfiles in one place helps keeping them similar, however, there will still be significant differences between applications/services.

In terms of build context, where would you keep the configuration files that are required for the docker build? ([in this case](https://github.com/peterzen/dcrweb/tree/localization/dockerfiles/www), for example)

This writeup has some insights about the different approaches:

http://rancher.com/lessons-learned-building-a-deployment-pipeline-with-docker-docker-compose-and-rancher-part-1/

**Comment by jcvernaleo** [comment]
Total side issue, but are we actually using apache for that?  @dajohi usually goes nginx for everything I believe.

**Comment by peterzen** [comment]
It was much simpler to set up the content negotiation in Apache (the nginx solutions I found all seemed overly complex, though I admit I'm not well versed with nginx).  Same with the API, I went with the simplest image – there might be an nginx image with php but the ones I found were a bit sketchy on the php extension support).

**Comment by jcvernaleo** [comment]
I don't object to apache but I think @dajohi does.  Should probably ping him to see what he thinks.

**Pull request merged**
