### PR TITLE
New contributors Jan 2019

### LINKED ISSUE #484: Add new contributors batch - Dec 2019
@rmykolas, find portraits from: https://github.com/decred/dcrdesign/issues/93

### PR DESCRIPTION
**Pull request by rmykolas**
Fixes #484

### CODE REVIEW

**Comment by rmykolas** [comment]
Also fixes the Slack ID mismatches - all of the ones from #455 are verified and replaced

**Comment by degeri** [comment]
Can I be added to this ?

**Comment by linnutee** [comment]
@degeri the portraits are illustrated when there's a batch of several people ready. You can send yours straight to `@kart`on slack and she'll take it on in the next batch.

**Comment by degeri** [comment]
Thank you .will do

**Pull request merged**
