### PR TITLE
Update ar.json

### PR DESCRIPTION
**Pull request by Insaf01**

### CODE REVIEW

**Comment by jholdstock** [comment]
Hi @Insaf01, thanks for this. There is a mistake here which is causing the tests to fail. When you include speech mark `"` in your string it needs to have a backslash before it, like `\"`.

**Review by jholdstock — CHANGES_REQUESTED** [review]
Hi @Insaf01, thanks for this. There is a mistake here which is causing the tests to fail. When you include speech mark `"` in your string it needs to have a backslash before it, like `\"`.

**Comment by Insaf01** [comment]
Sorry about that, I've just fixed the \" mark

**Comment by jholdstock** [comment]
Included in #1072, thanks

**Comment by Insaf01** [comment]
Thank you

**Pull request closed without merging**
