### PR TITLE
add android and ios links to the cryptopower card on /wallets

### PR DESCRIPTION
**Pull request by dreacot**
Screenshot 2024-03-16 at 6 05 49 PM

### CODE REVIEW

**Comment by dreacot** [comment]
@xaur the changes have been effected

**Comment by xaur** [comment]
Looks great thank you!

**Comment by xaur** [comment]
v1.1.2 is out, we might switch to that while this is not merged:

- https://github.com/crypto-power/cryptopower/releases/download/v1.1.2/cryptopower-v1.1.2.apk
- https://github.com/crypto-power/cryptopower/releases/tag/v1.1.2

**Comment by xaur** [comment]
@dajohi @jholdstock we can merge this as is and I'll make a small follow-up PR to update the two links to v1.1.2 to speed this up a bit. I can't push to this PR.

**Pull request closed without merging**
