### PR TITLE
Add DCRDEX to exchanges page

### PR DESCRIPTION
**Pull request by HlloWrld**
Added DCRDEX to exchanges page. Had to make background for DCRDEX image black; white DCRDEX logo font does not show on default white background.

Please let me know if I've done anything wrong I am eager to learn.

### CODE REVIEW

**Review by jholdstock — CHANGES_REQUESTED** [review]
Hey there, thanks for your contribution.

To automatically close the #924 issue, please update your PR description [per this documentation](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) (we don't include issue numbers in PR titles, only in the description). 

The logo on your image is not centred, it is too low. I reviewed the dcrdex package from [decred/dcrdesign](https://github.com/decred/dcrdesign/releases) and the preferred background color is dark blue. I have created a more appropriate image for you to use here.

dcrdex

**Comment by HlloWrld** [comment]
Thanks for the feedback. 

I'd originally centered the image but it bumps the logo and puts it off center. I'd purposely spaced it that way so it centers when the page loads. Let me know if you prefer it this way.

Purposely off centered image:
image2

Centered image:
image1
 
Please let me know which you prefer and I will submit a pull request (I will update to blue background on the original if you prefer the spacing on that)

**Comment by jholdstock** [comment]
The off-centre placement of the images is a separate issue, and it applies to all of the listed exchanges. All of the images being centred consistently is better than having just one image which is different.

**Comment by HlloWrld** [comment]
Resolves issue #924

**Review by jholdstock — APPROVED** [review]

**Pull request merged**
