### PR TITLE
Replace svgs with gifs on history page

### LINKED ISSUE #891: Implement symbol hover animations to /History/Principles
1. The symbols in the History subpage, 3rd section "Decred Community Principles" have hover animations ready for implementation. These are all made in json and as a simple solution can just trigger on hover (the animation for the next symbol) – or alternatively play it back once after being clicked. Hard to say which works best without testing. If something feels wonky or got any ideas to make more elaborate use of the animations via click/selected states, feel free to experiment + post previews here. 

All the animated assets can be found from: https://github.com/decred/dcrdesign/issues/206

Website20
https://lottiefiles.com/share/rIBrHW - privacy
https://lottiefiles.com/share/X1a13x - free speech consideration
https://lottiefiles.com/share/r81jI1 - open source software
https://lottiefiles.com/share/agg1dU - stakeholder inclusivity
https://lottiefiles.com/share/hs099H - universal fungibility
https://lottiefiles.com/share/0iuVGr - fixed finite supply
@kyleFirethought for help on animation specifics if needed. 

2. Also the principle names selected state should change to color to #ffffff and hover to #70CBFF (currently all of them remain as default #091440, regardless of state) 

Screenshot 2020-07-07 at 15 14 54

### PR DESCRIPTION
**Pull request by jholdstock**
Preview at https://testnet-vsp.jamieholdstock.com/history/

I've exported the animations from Lottie as .gifs to avoid adding extra js bloat to the website.

Fixed the active/hover colors.

Closes #891

### CODE REVIEW

**Comment by kyleFirethought** [comment]
principles_universalFungibility
principles_fixedfiniteSupply
I've removed a blank frame that is present on these 2 gifs generated. 
Other than that, all looks good.

**Comment by jholdstock** [comment]
Thanks Kyle, I've pushed a new commit to the PR and updated the preview site

**Comment by linnutee** [comment]
Hmm well gifs work reasonably, though I'd question whether the json animations are optimal here as these won't need any third-party js afaik? 

Quality-wise they are significantly sharper than gifs. Not sure on performance + size? Would assume they might be smaller than gifs?

**Comment by linnutee** [comment]
The active/hover colors should be for the full component, right now seems only the stroke changes color.
Screenshot 2020-07-08 at 15 34 07

Screenshot 2020-07-08 at 15 34 03

**Comment by jholdstock** [comment]
The JSON version of the animation is essentially just a configuration file for the [lottie web-player](https://lottiefiles.com/web-player) - a JavaScript based animation player. 

Having looked more closely, I think I'm actually going to add the web-player to the PR:
- Lottie web-player is *extremely* small in size compared to gifs (~100KB vs ~3MB)
- The player does not have any external dependencies, and does not call any external resources, so it should be easy to self host
- We can potentially use Lottie in other parts of the site with minimal additional cost

The only additional work required would be to add some static fallback images for no-js browsing, and we already have those available.


---

I cannot recreate your hover issue - on FF and Chrome I am seeing the behaviour you specified. What browser are you using?

**Comment by linnutee** [comment]
Hover issue appears on both Firefox 77. on macbook pro 10.15 as well on Firefox 76. on imac 10.14.6. 

Both instances on Safari and Chrome looks okay though. 

Animations actually look pretty good on just active state as well. My initial concern was that perhaps they might be too intrusive if looping, but since they're quite small symbols its not an issue.

**Comment by jholdstock** [comment]
Tried to reproduce this on Firefox 75/78 and still can't get it to occur. Can you check if any browser extensions are interfering? Any cached .css resources? (hard refresh & clear cache).

The css rule controlling this behaviour is very simple so I can't really imagine any scenarios how it could be broken:

https://github.com/decred/dcrweb/blob/14301a362dce48503043b087d717eba0c0eed556/src/assets/css/decred-v5.css#L3170-L3172

https://github.com/decred/dcrweb/blob/14301a362dce48503043b087d717eba0c0eed556/src/assets/css/decred-v5.css#L3148-L3150

**Comment by jholdstock** [comment]
Preview site and PR updated using Lottie web-player: https://testnet-vsp.jamieholdstock.com/history/
Using the previous static images as a no-js fallback.

@kyleFirethought please review the privacy icon on Lottie, it seems like the eye appears on a frame where it shouldnt be there.

**Comment by kyleFirethought** [comment]
Good to know the implementation was pretty seamless here. 

@jholdstock Here is an updated version of the JSON with the problem fixed: https://lottiefiles.com/27509-privacy

**Comment by jholdstock** [comment]
Thanks @kyleFirethought, PR and preview site updated. 

@linnutee @kyleFirethought - now that we have lottie web-player integrated into the site, and a huge library of animations to pick from, we are able to sprinkle some more motion into the site with very minimal effort. Please feel free to open new issues if anything comes to mind.

**Comment by linnutee** [comment]
@jholdstock: cheers, everything else looks very good, only the color issue above still remains. Seems this is only specific to macos and firefox, not getting on firefox on windows. 

Screenshot 2020-07-20 at 16 08 15
Screenshot 2020-07-20 at 16 04 24

**Comment by jholdstock** [comment]
Could you please try once more @linnutee? I think it's sorted.

**Comment by xaur** [comment]
It's minor, but changing PR title would avoid confusion since it was decided to use Lottie over gifs.

**Pull request merged**
