### PR TITLE
Fix nginx redirect

### PR DESCRIPTION
**Pull request by ZeroASIC**
This should fix the forward from /stakepools/ to /vsp/.  I didn't get the commit in before Pull Request #435 got merged in.

### CODE REVIEW

**Comment by peterzen** [comment]
`src/static/videos/headers/stakepools` needs to be renamed as well @ZeroASIC

**Comment by ZeroASIC** [comment]
@peterzen I think I fixed it in the most recent commit.  You can give it another test if you want to.

**Comment by peterzen** [comment]
The `301` redirect is now fine.  The port is still lost (there would have to be an `$http_host:$some_port_variable` or somesuch for that to work), but I guess it's OK since the port is always implicit in production so this can only bite us in dev mode when the redirect won't happen anyway.

**Comment by ZeroASIC** [comment]
That's odd, it keeps the port on my machine.  I start docker with -p 8080:80 and access it via http://local_ip:8080/stakepools/ and it forwards the way I expected it to.

**Comment by ZeroASIC** [comment]
> please remove additional video changes.

I deleted that commit and added a new one that didn't include the video folder.

**Pull request merged**
