### PR TITLE
[WIP] Onboarding tour update

### PR DESCRIPTION
**Pull request by Jujhar**
Addresses #409

To do might include new images especially for governance and Politeia, details about wallet use cases, and maybe three types of mining.

I decreased the opacity of images on the tour it seems to look better, creating an pleasent isolation between tour and rest of homepage.

Screen Shot 2019-06-01 at 5 33 14 PM
Screen Shot 2019-06-01 at 5 33 43 PM
Screen Shot 2019-06-01 at 5 34 08 PM
Screen Shot 2019-06-03 at 12 21 55 PM
Screen Shot 2019-06-01 at 5 34 40 PM
Screen Shot 2019-06-01 at 5 34 52 PM
Screen Shot 2019-06-01 at 5 35 04 PM
Screen Shot 2019-06-01 at 5 35 26 PM
Screen Shot 2019-06-01 at 5 35 38 PM
Screen Shot 2019-06-01 at 5 35 15 PM
Screen Shot 2019-06-01 at 5 36 02 PM

### CODE REVIEW

**Comment by linnutee** [comment]
@Dustorf should review the content. 

Shouldn't release anything with placeholder images. 

Don't see any good reason to change the image opacity, just makes them less informative. This should remain at 100%. If any image makes a harsh contrast, that can be tweaked individually.

**Comment by Jujhar** [comment]
Did you view the project in browser? The thing special about it is in the onboarding section the background is black/darker so introducing this soft overlay seems to mix well. It's at 0.8 opacity so it should be as informative as the other one. 

I need images for Governance and Politeia. I was thinking some very simplified bright illustrated versions of these two might be good? 

notes-1209639_960_720
Turkey_2018_elections,_ballots

**Comment by linnutee** [comment]
The way images are displayed has a common approach, and they’re not half transparent anywhere. So individual subjective preferences don’t outweigh a larger common approach.

Most of the images will be UI shots where possible, so those shouldn't be less clear. 

If anything has an icon, those are already using colors that are picked to blend well together and fit this context – meaning half transparency will only produce muddier random color values.

**Comment by Jujhar** [comment]
Got a snapshot for Politeia from it's homepage what should I use for governance?

**Comment by linnutee** [comment]
I won't address this one atm. As there's a larger overhaul in progress for the landing page, the tour section will likely be removed/or placed on other subpages. 

This is also mainly a content creation task, the textual content could be much further refined, so people from #writers-room and @Dustorf need to be involved.

**Comment by xaur** [comment]
I have mixed feelings about using stock images in general. Speaking of those [two images](https://github.com/decred/dcrweb/pull/672#issuecomment-498837407) specifically, if they show a ballot as I think, it's not a good idea to make a reference to traditional election systems.

**Comment by dajohi** [comment]
Closing.

**Pull request closed without merging**
