### PR TITLE
news: Add 3 software releases, 1 DJ, 1 coverage item

### PR DESCRIPTION
**Pull request by xaur**

### CODE REVIEW

**Comment by xaur** [comment]
Adding two Cryptopower releases to `software_releases.yml` since we have it in the Wallets now and it has two approved proposals.

Also adding one BR release. We need the News page to be more alive.

Suggesting a Reddit link for the first time, since it was an insightful exchange with a lead dev. Open to feedback if we want Reddit links in there.

Happy to tweak any changes ofc.

**Comment by xaur** [comment]
@jholdstock will it build if I just use `software: cryptopower` in `software_releases.yml` or do I also need to add an entry to `software.yml`?

**Comment by jholdstock** [comment]
Need an entry in `software.yml` and an icon added to `software-icons` folder. @dreacot are you able to provide an icon? Preferably .svg with a transparent background.

**Comment by xaur** [comment]
When #1173 is merged we can repurpose this PR for Cryptopower items only

**Comment by dreacot** [comment]
Cryptopower icon Asset

**Comment by jholdstock** [comment]
Thanks opened #1176

**Pull request closed without merging**
