### PR TITLE
Add Coinwale to list of exchanges

### PR DESCRIPTION
**Pull request by punit2502**

### CODE REVIEW

**Comment by jzbz** [comment]
You're commit references `Coinwale.jpg` but the file you uploaded is `Coinwale.png`.
Aside from that, we don't add exchanges without them first being vetted by a member of the community so we're sure they actually work.

**Comment by punit2502** [comment]
Sure, you (or someone from your team) can go ahead to check if exchange actually works or not.

**Comment by jholdstock** [comment]
Reviewed and tested the code changes. This is good to merge once the exchange has been validated

**Comment by dajohi** [comment]
@punit2502 why did you close?

**Comment by punit2502** [comment]
We are rebranding our website atm. Will create a new PR once we are done.

**Pull request closed without merging**
